### ISSUE TITLE
Could you please add more samples to understand?

### ISSUE THREAD

**Issue by insomniatt** [apptik/RHub#20]

**Comment by djodjoni** [comment]
There are covering almost all uses, however I am working on clear guide as just samples might be difficult to understand :) PRs are always welcome :)

**Comment by insomniatt** [comment]
It is easy to understand. But I have complex events callback I want to reconstruct by rx.
For example:
(1). broadcast : listen to bluetooth turn on/off
(2). broadcast : listen to audio jack plug in/out
(3). music view : change play/pause button by earphone jack plug in/out or bluetooth earphone connected
(4). custom events callback : (these 4 events are serial execution 1 by 1)
 -step 1 listen to custom bluetooth earphone connected (change ui: change app background color)
 -step 2 send shell event to get custom bluetooth earphone battery (change ui: show bt earphone battery in UI)
 -step 3 send event3 to get result3 from custom bluetooth earphone (change UI 3)
 - step 4 send event4 to get result4 from custom bluetooth earphone (change UI 4)
- init finish listen to disconnect or plug out
(5) listen to custom bluetooth earphone
- listen to button1 in bt earphone 
-listen to button2 in bt earphone
-listen to ...

**Comment by djodjoni** [comment]
well in the current examples you have clicks from 2 views going in which which is observed by an observer and may trigger data from 2 sensors coming in, which is listened to by another 2 observers. 
So you have small chain. Yours seems more complicated but the logic is the same.

The best I have found to design this is to identify different components, put them tags and clarify their function:

- only provides data

- only reads data

- provides data but also needs input

then you can design your inputs and outputs (shell interface).

To help visualise the whole thing you can draw the components and how they link. It is nice also to improve the flow

I will gladly help you to do this and put more complex scenario in the examples.
