### ISSUE TITLE
Unable to find implementation for interface io.apptik.rhub.exampleapp.Shield

### ISSUE THREAD

**Issue by insomniatt** [apptik/RHub#21]
I try to learn from the example app.
After create a new android app by Android Studio, merge exampleapp to hear, and then fixed dependency in build.gradle
    compile 'io.apptik.rhub:core:0.2.0-alpha1'
    compile 'io.apptik.rhub:rxjava-v1:0.2.0-alpha1'
    compile 'io.apptik.rhub:rxjava-v2:0.2.0-alpha1'
    compile 'io.apptik.rhub:shield-processor-rxjava1:0.2.0-alpha1'
    compile 'io.apptik.rhub:shield-base-processor:0.2.0-alpha1'
    compile 'io.apptik.rhub:shield-maker-rxjava1:0.2.0-alpha1'
I faced an issue: about Unable to find implementation for interface io.apptik.rhub.exampleapp.Shield

![image](https://cloud.githubusercontent.com/assets/853376/22876335/32a87a2e-f20b-11e6-945f-3a89438f24fe.png)

**Comment by djodjoni** [comment]
it seems that the processor didn't generate the shield implementation. did you change the shiled interface? which version of build tools do you use ?

**Comment by insomniatt** [comment]
@djodjoni 
1.build tools config is below: 
`android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"}`
2.Shiled interface is below:
![image](https://cloud.githubusercontent.com/assets/853376/22908413/4b1abbf2-f289-11e6-98a5-5a91b2e58712.png)

**Comment by djodjoni** [comment]
can you show me you full gradle please

**Comment by djodjoni** [comment]
sorry my bad i didn't see how include the processors.

all processors you need to use with `annotationProcessor` instead of `compile`


so you culd write:

compile 'io.apptik.rhub:rxjava-v1:0.2.0-alpha1'
annotationProcessor 'io.apptik.rhub:shield-processor-rxjava1:0.2.0-alpha1'
compile 'io.apptik.rhub:shield-maker-rxjava1:0.2.0-alpha1'

**Comment by djodjoni** [comment]
@insomniatt did this work for you ?

**Comment by insomniatt** [comment]
@djodjoni 
Yes, it is running. Thank you very much.
And this is my dependency:
`
    compile 'io.apptik.rhub:rxjava-v1:0.2.0-alpha1'
    compile 'io.apptik.rhub:rxjava-v2:0.2.0-alpha1'
    compile 'io.apptik.rhub:shield-maker-rxjava1:0.2.0-alpha1'
    compile 'io.apptik.rhub:shield-annotations:0.2.0-alpha1'
    annotationProcessor 'io.apptik.rhub:shield-processor-rxjava1:0.2.0-alpha1'
    annotationProcessor 'io.apptik.rhub:shield-base-processor:0.2.0-alpha1'
`

**Comment by djodjoni** [comment]
great :) btw you dont need compile 'io.apptik.rhub:rxjava-v2:0.2.0-alpha1'
 as it seems you dont use rxjava2
